<?php

namespace Ens\JobeetBundle\Repository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDescriptions()
	{
		$em = $this->getEntityManager();
		$query = $em->createQuery(
				'SELECT c.description FROM EnsJobeetBundle:Category c'
				);
				
				return $query->getResult();
	}
	
	public function getLow(){
		
		$em = $this->getEntityManager();
		$query = $em->createQuery(
				'SELECT c FROM EnsJobeetBundle:Level c WHERE c.description = :description'
				)->setParameter('description', 'Low');
		
		return $query->getResult();
		
	}
}
