ens_jobeet:
    resource: "@EnsJobeetBundle/Controller/"
    type:     annotation
    prefix:   /

ens_job_homepage:
    path:     /
    defaults: { _controller: EnsJobeetBundle:Job:index }
    

app:
  resource: '@AppBundle/Controller/'
  type: annotation